# Generated by Django 5.0.6 on 2024-05-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraductorInfoAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='user',
        ),
        migrations.AddField(
            model_name='documents',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documents',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
